# Generated by Django 5.1.3 on 2024-11-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/')),
            ],
        ),
    ]
